### ISSUE TITLE
ImportError: cannot import name JIRA

### ISSUE THREAD

**Issue by spy86** [abhijith0505/JIRA-ticket-creationg-using-zabbix-alerts#1]
Hello,

I try test this and after running I receive error :

`Traceback (most recent call last):
  File "jira.py", line 4, in <module>
    from jira import JIRA
  File "/root/JIRA-ticket-creationg-using-zabbix-alerts/jira.py", line 4, in <module>
    from jira import JIRA
ImportError: cannot import name JIRA
`

**Comment by wqsudotee** [comment]
I imagine the issue is that your file is called jira.py. try renaming it.

**Comment by abhijith0505** [comment]
Yes, @wqsudotee is right.
For ref, https://stackoverflow.com/questions/41621566/python-cannot-import-name-jira
